### ISSUE TITLE
Recognize file paths whether in UNIX/Linux or Windows syntax

### ISSUE THREAD

**Issue by asapnet** [Veremes/rTest#9]
I run FME Desktop on Mac OS X, which is derived from BSD UNIX.  Our servers run various flavors of Linux.  File paths in scenario files should probably work the same whether the scenario is executed under Windows or not.

**Comment by ogayte** [comment]
Bo Guo sent me the same problem by email with a proposal for the new Python code.
I have just posted the new version of ScenarioPlayer.fmw

**Comment by asapnet** [comment]
@ogayte Can you send out a pull request for the latest changes so I can merge into my fork?

**Comment by ogayte** [comment]
I am afraid I am not able to do that. I have posted directly on the branch so I thought It was useless. I will discuss that point with my development team tomorrow in the morning and we will fix it very soon. Sorry for the delay.

**Comment by asapnet** [comment]
No worries, I can fast-forward from my command line in the meantime.  Support for pull requests would be useful with collaborators in the mix.

**Comment by asapnet** [comment]
As I research the version control options for FME workspaces, I'm thinking that forks are not the way to go, at least not to start.  Testing an existing tool that needs a central repository with simple branching rather than forked repos.

**Comment by AlexandreBizien** [comment]
Hey @asapnet , I assume you don't need anymore of that pull request so I've closed the thread. Feel free to ask us another pull request whenever you want.
